server:
  port: ${kedou.port:8077}
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${kedou.datasource.host:localhost}:${kedou.datasource.port:3306}/${kedou.datasource.database:kedou}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${kedou.datasource.username:root}
    password: ${kedou.datasource.password:123}
  profiles:
    active: dev
  servlet:
    multipart:
      #配置单个文件上传大小的限制（SpringBoot中默认的限制是1MB）
      max-file-size: 10MB
      #配置单个请求大小的限制（一个请求可以上传多个文件）（SpringBoot中默认的限制是10MB）
      max-request-size: 100MB

#MyBatis-Plus相关配置
mybatis-plus:
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml # Mapper.xml文件地址，当前这个是默认值。
  type-aliases-package: com.yubar.kedou.mapper
kedou:
  profile: /static/logo_out.png  # 默认头像位置
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: admin
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 用户端
    user-secret-key: user
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${kedou.alioss.endpoint}
    access-key-id: ${kedou.alioss.access-key-id}
    access-key-secret: ${kedou.alioss.access-key-secret}
    bucket-name: ${kedou.alioss.bucket-name}
  wechat:
    appid: ${kedou.wechat.appid}
    secret: ${kedou.wechat.secret}
  upload:
    mode: ${kedou.upload.mode}  # 上传文件模式：LOCAL:本地上传  CLOUD：云存储
    base-path: ${kedou.upload.base-path} #如果使用本地上传，指定本地保存基路径
    return-base-path: ${kedou.upload.return-base-path}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    title:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '用户端'
      paths-to-match: '/**'
      packages-to-scan: com.yubar.kedou.controller.user
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  documents:
    - group: 1.0版本
      name: Yubar
      locations: classpath:sign/*
  setting:
    language: zh_cn
    footer-custom-content: Copyright @ Yu-Bar (https://github.com/Yu-Bar)
    # 自4.1.0版本开始，替代home-custom-location属性，开发者请使用该配置
    enable-home-custom: true
    home-custom-path: classpath:MarkDown/readme.md

